name: Checking all test

on:
  pull_request:
    branches: [ "master"]

jobs: 
  build:
    strategy:
      matrix:
        configuration: [ "Debug", "Release" ]

    runs-on: ubuntu-latest

    env:
      Solution_Name: Dotnet_Base_Backend.sln
      Test_Project: Dotnet_Base_Backend.API.Tests.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Execute unit test
        run: dotnet test

      - name: install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: SonarCube - SonaCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
             dotnet build --no-incremental
             dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
             dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
